services:
  stonksexchange-checker:
    build: .
    ports:
      - 8198:8000
    environment:
     - MONGO_ENABLED=1
     - MONGO_HOST=stonksexchange-checker-db
     - MONGO_PORT=27017
     - MONGO_USER=enoislove
     - MONGO_PASSWORD=enoislife1338
  stonksexchange-checker-db:
    image: mongo
    volumes:
      - ./stonksexchange-checker-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: enoislove
      MONGO_INITDB_ROOT_PASSWORD: enoislife1338
